### PR TITLE
chore: Use dependabot

### PR DESCRIPTION
**Pull request by acroos**
Simply enabling dependabot so we can stop using depfu

### CODE REVIEW

**Review by grdw — APPROVED** [review]

**Comment by acroos** [comment]
oh.... I can't actually merge this because it requires my review, which I can't give because I opened it.  how did this ever work in the past?

**Comment by acroos** [comment]
@isabellabrookes can you give me super powers to be able to merge this somehow?  idk how I was able to create PRs in the past, but there's no way to merge a PR that I open in this repo.

**Comment by isabellabrookes** [comment]
@acroos sorry, missed this. Done ✨

**Comment by isabellabrookes** [comment]
fyi, it's owned by "transfer" right now. and you're probably not in the transfer team anymore.

**Review by nyku — APPROVED** [review]

**Pull request merged**
